name: Artifact

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Info
        run: |
          echo "version=$(grep -Eo '[0-9]+(\.[0-9]+)+' CHANGELOG.md | head -n 1)" >> $GITHUB_OUTPUT
        id: info
      - name: Build Artifact
        run: |
          cd ${{ github.workspace }}
          cwd=$(pwd)
          git submodule update --init --recursive
          mkdir -p ./onlyoffice
          rsync -av --exclude='onlyoffice' . onlyoffice
          cd onlyoffice
          rm -rf ./.github/
          rm -rf ./.git/
          rm ./.eslintrc.json
          rm ./.gitmodules
          rm ./.stylelintrc.json
          rm ./npm-shrinkwrap.json
          rm ./package.json
          rm ./ruleset.xml
          rm -rf ./assets/document-templates/.git
          rm -rf ./assets/document-formats/.git
          cd ./appinfo
          sed -i 's|<licence>apl2|<licence>agpl|' info.xml 
          cd $cwd
          tar -czvf onlyoffice.tar.gz onlyoffice
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: onlyoffice
          path: onlyoffice.tar.gz